import Head from "next/head";
import Header from "./Header";
import { ApolloProvider } from "@apollo/client";
import { AppProvider } from "./context/AppContext";
import client from "@/lib/apollo";

const Layout = (props) => {
  return (
    <AppProvider>
      <ApolloProvider client={client}>
        <div>
          <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1"
            />
          </Head>
          <Header />
          {props.children}
        </div>
      </ApolloProvider>
    </AppProvider>
  );
};

export default Layout;
