import Head from "next/head";
import Header from "./Header";
import { ApolloProvider } from "@apollo/client";
import { AppProvider } from "./context/AppProvider";
import client from "@/lib/apollo";

const Layout = (props) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <AppProvider>
        <ApolloProvider client={client}>
          <Header siteLogoUrl = {props.siteLogoUrl}/>
          {props.children}
        </ApolloProvider>
      </AppProvider>
    </>
  );
};

export default Layout;
