import Head from "next/head";
import client from "@/lib/apollo";
import Header from "./Header";
import { ApolloProvider } from "@apollo/client";

const Layout = (props) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <ApolloProvider client={client}>
        <Header siteLogoUrl={props.siteLogoUrl} />
        {props.children}
      </ApolloProvider>
    </>
  );
};

export default Layout;
